"""empty message

Revision ID: d63a10233516
Revises: 
Create Date: 2025-05-07 22:24:13.121977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd63a10233516'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('organization_name', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=100), nullable=False),
    sa.Column('contact_phone', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('organization_id'),
    sa.UniqueConstraint('contact_email'),
    sa.UniqueConstraint('organization_id'),
    sa.UniqueConstraint('organization_name')
    )
    op.create_table('branches',
    sa.Column('branch_id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('branch_name', sa.String(length=100), nullable=False),
    sa.Column('branch_location', sa.String(length=255), nullable=False),
    sa.Column('person_in_charge', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=100), nullable=False),
    sa.Column('contact_phone', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('branch_id'),
    sa.UniqueConstraint('branch_id'),
    sa.UniqueConstraint('contact_email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('branches')
    op.drop_table('organizations')
    # ### end Alembic commands ###
